### ISSUE TITLE
automate enrollement to support course

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#28]
it is only possible to book a virtual support meeting when the user is enrolled to the support course. Teachers and Managers should automatically be enrolled in the course when they click on "virtual support meeting". Student should not even see this option.

Make sure that the user cannot contact ZLM support directly after booking a virutal support meeting.

**Comment by rschrenk** [comment]
Dear Julia, we need a solution for this. Since today users are not enrolled to our support course automatically. In future the support course itself is not used anymore with enrolled users, guest access should suffit. I would suggest to move the organizer to another course with automated enrolment dedicated to the organizer only. This keeps the course small and we can regularly remove all participants. A link to this dedicated course can be set in the support course as well, but its user management is split from the main support course. Please tell me once you have created this dedicated course. Kind regards

**Comment by lassnj** [comment]
Course has been created: [https://www.eduvidual.at/course/view.php?id=54405](https://www.eduvidual.at/course/view.php?id=54405)

**Comment by rschrenk** [comment]
As agreed by Mail we will activate the new course in christmas holidays.
[ ] Don't offer slots in old organizer after christmas
[ ] Create slots after christmas in new organizer (mid of December)
[ ] Link to new organizer in description of old organizer (mid of December)
[ ] Deactivate old organizer after christmas
[ ] Link on upper right below "Create Issue" after christmas

**Comment by rschrenk** [comment]
I created us a card in our cloud, so we will be reminded on 14th of December.

**Comment by rschrenk** [comment]
@lassnj please prepare the according steps.

**Comment by lassnj** [comment]
- [x] Don't offer slots in old organizer after christmas
- [x] Create slots after christmas in new organizer (mid of December)
- [x] Link to new organizer in description of old organizer (mid of December)
- [x] Deactivate old organizer after christmas
- [x] Link on upper right below "Create Issue" after christmas

**Comment by lassnj** [comment]
automated enrolment dedicated to the organizer only is not possible as the organizer (Planer) cannot be selected. The course is available as guest access, link needs to go to overview-page so that the users can enroll before booking an appointment.
https://www.eduvidual.at/course/view.php?id=54405&section=0

**Comment by lassnj** [comment]
@rschrenk please change link in upper right below "Create Issue" to [https://www.eduvidual.at/course/view.php?id=54405&section=0](https://www.eduvidual.at/course/view.php?id=54405&section=0)

**Comment by rschrenk** [comment]
Done
